### ISSUE TITLE
The macro at the end to build the executable JAR is missing the production profile

### ISSUE THREAD

**Issue by DominiqueComte** [spring-guides/gs-crud-with-vaadin#114]
At the end of the tutorial, in the "Build an executable JAR" paragraph, the build instructions are missing the "production" profile that actually builds the frontend files to include in the JAR.

Without this, running the jar and trying to access the application produces an error page and this in the console:
```
java.lang.IllegalStateException: 

  Failed to find the following files: 
      - ./generated/jar-resources/lit-renderer.ts
      - ./generated/jar-resources/vaadin-time-picker/timepickerConnector.js
 [etc...]
```

includes in AsciiDoc do not seem to support a parameter that could contain the missing "-Pproduction" (for Maven), though.

**Comment by robertmcnees** [comment]
Hi @DominiqueComte. I went through the guide and I see the same thing. Using `./gradlew bootRun` will produce the desired results, but the instructions on the .jar file are incorrect. In addition to the problem you described in this issue the name of the .jar file is also incorrect. That is a common problem in our guides unfortunately.

You mention the AsciiDoc include files. Going forward I think we should favor correct information rather than standardized information if we have to choose one. That said, I think there is room for both using a [new standard file](https://github.com/spring-guides/getting-started-macros/blob/main/build_and_execute_guide.adoc). This is a pattern that I've implemented in a few guides, for example [RabbitMQ](https://spring.io/guides/gs/messaging-rabbitmq).

For this guide specifically, I think that we should update the sections to roughly track:

- Run the Application - `./gradlew bootRun`
- Preparing to Build the Application - modifying property files to set the profile
- Building the Application - if guide specific configuration is handled in the 'Preparing to Build the Application' section, then hopefully this can remain [common](https://github.com/spring-guides/getting-started-macros/blob/main/build_and_execute_guide.adoc).

**Comment by DominiqueComte** [comment]
Could the instructions remain standard by merging the `production` profile into the default build ?
This way the frontend is simply built by using the usual Maven goals.

**Comment by Buzzardo** [comment]
We should use includes only when they 100% match the need of the guide.

I am leaving this issue open in case you want to address it be merging the `production` profile.

**Comment by DominiqueComte** [comment]
I tried moving the contents of the "production" profile to the default build to avoid changing the build instructions, it works fine.
But when following the tutorial and generating the project from Spring Initializr, the production profile is there in the generated POM so the instructions still do not match.
